spring:
  application:
    name: skillbridge-api

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/skillbridge}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiry-ms: ${JWT_EXPIRY_MS:86400000} # 24 hours (86,400,000 ms)
  file:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads/resumes}